GET http://localhost:8080/api/users/testmail
Accept: application/json

###

POST http://localhost:8080/api/users
Accept: application/json
Content-Type: application/json

{
  "email": "testmail",
  "name": "Name111",
  "age": 111
}

###

PUT http://localhost:8080/api/users
Accept: application/json
Content-Type: application/json

{
  "email": "testmail",
  "name": "NewName",
  "age": 222
}

###

DELETE http://localhost:8080/api/users/testmail
Accept: application/json

###

GET http://localhost:8080/api/usermeta/testmail
Accept: application/json

###

POST http://localhost:8080/api/usermeta
Accept: application/json
Content-Type: application/json

{
  "email": "testmail",
  "hobby": "metahobby",
  "friendsEmails": ["friend8@meta.ru", "friend6@meta.ru"]
}

###

PUT http://localhost:8080/api/usermeta
Accept: application/json
Content-Type: application/json

{
  "email": "testmail",
  "hobby": "metahobby",
  "friendsEmails": ["newfriend1@meta.ru", "newfriend2@meta.ru"]
}

###

DELETE http://localhost:8080/api/usermeta/testmail
Accept: application/json


